name: separated_number_input_formatter
description: A TextInputFormatter that allows the insertion of digits separated by specified separator.
version: 0.0.1
author: Kosuke Kito <blueberryjam09@gmail.com>
homepage: https://github.com/kitoko552/separated_number_input_formatter
environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter